### ISSUE TITLE
Obrigado!

### ISSUE THREAD

**Issue by TiagoVentura** [nataliabueno/close_races#2]
Natália, Leonardo e Lucas, 

Obrigado por organizar este código! Estou trabalhando em uma replication para meu graduate seminar em Causal Inference, e o trabalho de vocês adiantou bastante o que precisava fazer para rodar minhas análises.  

Valeu!

**Comment by nataliabueno** [comment]
Oi Tiago, 

Obrigada pelo comentário! Se tiver alguma sugestão de como melhorar, fale por aqui. Abs!
