### ISSUE TITLE
Correção no código de download e consolidação de bases eleitorais

### ISSUE THREAD

**Issue by atrfisch** [nataliabueno/close_races#3]
Caros, primeiramente, parabéns pelo trabalho. Ele representa um grande ativo para toda a comunidade. Muito obrigado.

Estou utilizando pedaços dos códigos para montar a corrida entre primeiros suplentes e últimos eleitos para cargos proporcionais. Estou utilizando como parâmetro o código TSE_CEPESP_TEST.R.

Ao replicar os códigos de download, unzip e consolidação das bases de candidatos e munzona notei que algumas correções podem ser necessárias:

**1- Na linha 141, quando fazemos o download da votação de 2016, o objeto está apontando para a url de candidatos.  A alteração seria trocar:**

Como está: vot_2016 <- get_tse(url_cand16, file_d, file_un)
Como deveria ficar: vot_2016 <- get_tse(url_vot16, file_d, file_un)

**2- Labels de candidatos:**

- Linha 277: necessário mudar o nome do objeto de labels

Como está: names(cand_2012) <- labels_2012
Como deveria ficar: names(cand_2012) <- labels_2012c

-  Linha 302: necessário mudar o nome do objeto de labels

Como está: names(cand_2016) <- labels_2016
Como deveria ficar: names(cand_2016) <- labels_2016c

**3- Variaveis ufs.** 

Há no código um objeto com o nome ufs_n e as consolidações das voting data de 2002, 2006 e 2010 (linhas 440, 449, 458 respectivamente) chamam um objeto chamado ufs. O ideal seria incluir um _n para que puxasse o nome correto do objeto.

**Comment by nataliabueno** [comment]
@atrfisch Obrigada pelos comentários. Eu incorporei todas suas sugestões e já atualizei o repositório. Eu atualizei tanto o TSE_CEPESP_TSE. R quanto o TSE_repositorio.R, onde aplicável.
